# Generated by go2rpm
%bcond_without check

# https://pagure.io/golist
%global goipath         pagure.io/golist
# This is the real URL, but F29 forge macros don't support it.
#global forgeurl        https://pagure.io/golist
Version:                0.10.0

%gometa

%global common_description %{expand:
A tool to analyse the properties of a Go (Golang) codebase.}

Name:           golist
Release:        1%{?dist}
Summary:        A tool to analyse the properties of a Go (Golang) codebase

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
#Source0:        #{gosource}  # Not supported by current forge macros.
Source0:        https://pagure.io/golist/archive/v%{version}/golist-%{version}.tar.gz

BuildRequires:  golang(github.com/urfave/cli)

# Before split of /usr/bin/golist.
# Remove in Fedora 34.
Conflicts: go-compilers-golang-compiler < 1-34

%description
%{common_description}


%prep
#forgeautosetup -p1
%autosetup -p1 -n golist-%{version}


%build
%gobuildroot
for cmd in cmd/* ; do
  %gobuild -o _bin/$(basename $cmd) %{goipath}/$cmd
done


%install
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp _bin/*              %{buildroot}%{_bindir}/


%if %{with check}
%check
%gochecks
%endif


%files
%doc NEWS.md README.md
%license LICENSE
%{_bindir}/*


%changelog
* Mon May 27 01:19:35 EDT 2019 Elliott Sales de Andrade <quantum.analyst@gmail.com> - 0.10.0-1
- Initial package
